### ISSUE TITLE
🔧 Add docker container support

### ISSUE THREAD

**Issue by FranklinWaller** [sedaprotocol/seda-data-proxy#4]
## 🔧 Chore

Add support for a docker

## Motivation

Allows data providers to easily run a container with the settings they want

**Comment by kaynetik** [comment]
If I understood the intention behind this ticket, we want to enable data providers to initiate `config.json` to their own liking?

If that assumption is correct, then please verify that the following statements cover all possible statements @Thomasvdam .

## 1. Basic Structure
```json
{
  "routeGroup": "string",
  "routes": [
    {
      "path": "string",
      "upstreamUrl": "string",
      "method": "string" | ["string"],
      "headers": {
        "header-name": "string"
      },
      "jsonPath": "string",
      "forwardResponseHeaders": ["string"]
    }
  ]
}
```

## 2. Route Configuration

### 2.1 Path
- Simple path: `"/eth-usd"`
- Variable path: `"/:coinA/:coinB"`
- Wildcard path: `"/*"`

### 2.2 Upstream URL
- Simple URL: `"https://myapi.com/eth-usd"`
- URL with variables: `"https://myapi.com/{:coinA}-{:coinB}"`
- URL with wildcard: `"https://swapi.dev/api/{*}"`

### 2.3 Method
- Default (GET): Omit the "method" field
  - Or was this a wrong assumption? Should we require a method to be specified?
- Single method: `"method": "GET"`
- Multiple methods: `"method": ["GET", "HEAD"]`

### 2.4 Headers
```json
"headers": {
  "x-api-key": "string",
  "x-custom": "string"
  // Do we leave room for custom key-value header pairs?
}
```

### 2.5 JSON Path
```json
"jsonPath": "$.name"
```

### 2.6 Forward Response Headers
```json
"forwardResponseHeaders": ["content-type", "server"]
```

## 3. Variable Injection

### 3.1 Route Variables
- In path: `"/:varName"`
- In upstream URL: `"{:varName}"`
- In headers: `"x-custom": "{:varName}"`

### 3.2 Environment Variables
- In headers: `"x-api-key": "{$SECRET_API_KEY}"`
- Can be used in any string field

### 3.3 Wildcard
- In path: `"/*"`
- In upstream URL: `"{*}"`

## 4. Example
```json
{
  "routeGroup": "proxy",
  "routes": [
    {
      "path": "/:coinA/:coinB",
      "upstreamUrl": "https://myapi.com/{:coinA}-{:coinB}",
      "method": ["GET", "HEAD"],
      "headers": {
        "x-api-key": "{$SECRET_API_KEY}",
        "x-custom": "{:coinA}"
      },
      "jsonPath": "$.price",
      "forwardResponseHeaders": ["content-type", "server"]
    },
    {
      "path": "/planets/*",
      "upstreamUrl": "https://swapi.dev/api/planets/{*}",
      "jsonPath": "$.name",
      "headers": {
        "x-api-key": "some-api-key"
      }
    }
  ]
}
```

**Comment by kaynetik** [comment]
Also, is the `.env.example` up to date?

**Comment by Thomasvdam** [comment]
Honestly I'm not sure where we want to draw the line for the scope of this issue. Maybe to keep it manageable we can use this issue for the bare minimum:
- Create a docker image
  - Think about how to deal with the `init` (create key and config), `register` (register the proxy on chain along with some settings), and the `run` commands (actually run the proxy, needs a private key and valid config).
  - Think about how to manage the private key used for signing the data.
  - Manage the options and env variables.
- Add a pipeline that publishes docker images.
- Probably more :D

Improving the setup with the config can be left as a separate task, if we have the above the users should be able to edit the config.json on the machine or upload one from their local machine.

**Comment by kaynetik** [comment]
I might need you next week to see this in action, in order to properly grasp the complete scope and do adequate automation. Tnx @Thomasvdam 🚀
